config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  resources :transactions, only: [:show, :index] do
    collection do
      get :deposit
      get :withdraw
      get :transfer
      put :deposit_update
      put :withdraw_update
      put :transfer_update
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :generate_account_number

  has_many :transactions

  private

  def generate_account_number
    self.update(account_no: SecureRandom.base58(12))
  end

  def self.deposit(user, amount, recipient_id)
    new_balance = user.total_balance + amount
    if user.update(total_balance: new_balance)
      user.transactions.create(transaction_type: "deposit", amount: amount, recipient_id: recipient_id)
    end
  end

  def self.withdraw(user, amount, recipient_id)
    new_balance = user.total_balance - amount
    if user.update(total_balance: new_balance)
      user.transactions.create(transaction_type: "withdraw", amount: amount, recipient_id: recipient_id)
    end
  end

  def self.get_user_name(id)
    user_name = User.find_by(id: id).first_name.titleize + user.last_name.titleize
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    added_attrs = [:first_name, :last_name, :mobile, :account_type]
    devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def deposit
  end

  def show
  end

  def withdraw
  end

  def transfer
  end

  def index
    @transactions = current_user.transactions
  end

  def deposit_update
    amount = params[:transaction][:amount]
    if amount > 0
      User.deposit(current_user,amount.to_f, nil)
      flash[:success] = "Your balance is updated."
    end
    redirect_to root_path
  end

  def withdraw_update
    amount = params[:transaction][:amount].to_f
    if current_user.total_balance > amount
      User.withdraw(current_user, amount, nil)
      flash[:success] = "Your balance is updated."
    else
      flash[:danger] = "Sorry you don't have enough balance!"
    end
    redirect_to root_path
  end

  def transfer_update
    amount = params[:user][:amount].to_f
    if current_user.total_balance > amount
      recipient_user = User.find_by(account_no: params[:user][:account_no])
      if recipient_user.present?
        User.withdraw(current_user, amount, recipient_user.id)
        User.deposit(recipient_user, amount,recipient_user.id)
        flash[:success] = "Transfer amount is done successfully."
      end
    else
      flash[:danger] = "Sorry you don't have enough balance!"
    end
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/home/index.html.erb
<% flash.each do |key, value| %>
  <div class='<%= "alert alert-#{key} alert-dismissible" %>'>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= value %>
  </div>
<% end %>
<h3 class="text-center">Welcome <%= current_user.first_name.titleize + current_user.last_name.titleize %></h3>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="#">Bank Application</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Deposit", deposit_transactions_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Withdraw money", withdraw_transactions_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Transfer money", transfer_transactions_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "View balance", transaction_path(current_user.id), class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "View transaction", transactions_path, class: "nav-link" %>
      </li>
    </ul>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-outline-success my-2 my-sm-0" %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BankApplication</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render partial: "layouts/header" %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/transactions/deposit.html.erb
<%= form_for :transaction, url: deposit_update_transactions_path, method: :put do |f| %>
  Amount: <%= f.number_field :amount %><br />
  <%= f.submit %>
<% end %>

app/views/transactions/index.html.erb
<h3 class="text-center">Bank Statement</h3>
<table class="text-center w-100">
  <thead>
    <th>Sr.no</th>
    <th>Date</th>
    <th>recipient name</th>
    <th>Withdraw</th>
    <th>Credit</th>
    <th>Balance</th>
  </thead>
  <tbody>
    <% total_balance = 0 %>
    <% @transactions.each_with_index do |transaction,index| %>
      <tr>
        <td><%= index+1 %></td>
        <td><%= transaction.created_at.strftime("%d-%m-%Y") %></td>
        <td class="text-center"><%= transaction.recipient_id.present? ? User.get_user_name(transaction.recipient_id) : "-" %></td>
        <td><%= transaction.transaction_type == "withdraw" ? transaction.amount : "-" %></td>
        <td><%= transaction.transaction_type == "deposit" ? transaction.amount : "-" %></td>
        <td>
          <% if transaction.transaction_type == "deposit" %>
            <%= total_balance = total_balance + transaction.amount %> Rs
          <% elsif transaction.transaction_type == "withdraw" %>
            <%= total_balance = total_balance - transaction.amount %> Rs
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/transactions/show.html.erb
<h4 class="text-center"><b>User:</b><%= current_user.first_name.titleize + current_user.last_name.titleize %></h4>
<h4 class="text-center"><b>Account No:</b><%= current_user.account_no %></h4>
<h4 class="text-center"><b>Total Balance:</b><%= current_user.total_balance %></h4>

app/views/transactions/transfer.html.erb
<%= form_for :user, url: transfer_update_transactions_path, method: :put do |f| %>
  Recipient account no: <%= f.text_field :account_no %><br />
  Amount: <%= f.number_field :amount %><br />
  <%= f.submit %>
<% end %>

app/views/transactions/withdraw.html.erb
<%= form_for :transaction, url: withdraw_update_transactions_path, method: :put do |f| %>
  Amount: <%= f.number_field :amount %><br />
  <%= f.submit %>
<% end %>